# navbar
menu:
  Home: /
  Archives: /archives/
  Tags: /tags/
  About: /about/

# site icon
favicon: /favicon.ico

# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default

# comments
comments:
  post: true
  about: true

# article contents sidebar
sidebar: true

# Analytics
## Baidu Analytics
baidu_analytics: b54ec1817ee20d83af77a0859c4dda5d
## Google Analytics
google_analytics: UA-74273646-1

# Comments
## Duoshuo
duoshuo_shortname: ahonn
## Disqus
disqus_shortname: ahonn

# Social links
social:
  email: ahonn95@outlook.com
  stack-overflow:
  twitter:
  facebook:
  github: https://github.com/ahonn 
  weibo: 
  zhihu: https://www.zhihu.com/people/ahonn/activities
  rss: /atom.xml